---
- hosts: all
  sudo: true
  gather_facts: no


  pre_tasks:
    - name: install python if it is not there already
      raw: apt-get update && apt-get -y install python
    - name: Gathering facts
      setup:

  roles:
    - generic

  tasks:
    - name: set LC_ALL
      lineinfile: dest=/etc/bash.bashrc state=present line="export LC_ALL=C"

    - stat: path=/usr/bin/docker
      register: docker

    - name: fetch docker install script
      get_url: url=https://get.docker.com dest=/tmp/install-docker.sh mode=0555
      when: not docker.stat.exists

    - name: install docker
      shell: /tmp/install-docker.sh
      when: not docker.stat.exists

    - name: add default user to docker group
      user: name="{{ansible_user}}" groups=docker append=yes

