VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # config.vm.box = "ubuntu/xenial64"
  config.vm.box = "bento/ubuntu-16.10"
  #config.vm.box = "bento/ubuntu-16.04-i386"
  config.vm.provider "virtualbox" do |vb|
     vb.cpus = 3
     vb.customize ["modifyvm", :id, "--memory", "2048"]
  end

  config.vm.provision :ansible do |ansible|
    ansible.playbook = "provision.yaml"
  end
end
