VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "bento/ubuntu-16.10"

  config.vm.provider :aws do |aws, override|
     aws.instance_type = "t2.medium"
     # aws.iam_instance_profile_name = 'ecsecrfull'
     # aws.iam_instance_profile_name = 'swarmnode'
  end

  config.vm.provision :ansible do |ansible|
    ansible.playbook = "provision.yaml"
  end
end
